// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Owl is an autogenerated mock type for the Owl type
type Owl struct {
	mock.Mock
}

// Errorf provides a mock function with given fields: format, args
func (_m *Owl) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *Owl) FailNow() {
	_m.Called()
}

// IsVerbose provides a mock function with given fields:
func (_m *Owl) IsVerbose() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Printf provides a mock function with given fields: format, a
func (_m *Owl) Printf(format string, a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}

// Println provides a mock function with given fields: a
func (_m *Owl) Println(a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}
